// Emits src/generated/routes.ts — operationId → { method, path } — from the
// SDK OpenAPI snapshot, so resource methods can never drift from the contract.
//
// Usage: node scripts/generate-routes.mjs <openapi.json> <out.ts>
import { readFileSync, writeFileSync } from 'node:fs';

const [input, output] = process.argv.slice(2);
if (!input || !output) {
  console.error('usage: generate-routes.mjs <openapi.json> <out.ts>');
  process.exit(2);
}

const METHODS = ['get', 'put', 'post', 'patch', 'delete'];
const doc = JSON.parse(readFileSync(input, 'utf8'));
const rows = [];
for (const [path, item] of Object.entries(doc.paths)) {
  for (const method of METHODS) {
    const op = item[method];
    if (op?.operationId) rows.push([op.operationId, method.toUpperCase(), path]);
  }
}
rows.sort(([a], [b]) => a.localeCompare(b));

const body = rows
  .map(([id, method, path]) => `  ${id}: { method: '${method}', path: '${path}' },`)
  .join('\n');

writeFileSync(
  output,
  `// Generated by scripts/generate-routes.mjs from packages/sdk-spec/openapi.json — do not edit.
import type { operations } from './openapi';

export type OperationId = keyof operations;

export const ROUTES = {
${body}
} as const satisfies Record<OperationId, { method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'; path: string }>;
`,
  'utf8',
);
